name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant permission
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew assemble
      - name: Test
        run: ./gradlew testReleaseUnitTest
      - name: lint
        if: github.event_name  == 'pull_request'
        run: ./gradlew lintRelease
      - uses: actions/upload-artifact@v1
        if: github.event_name  == 'pull_request'
        with:
          name: testResult
          path: app/build/test-results/testReleaseUnitTest
      - uses: actions/upload-artifact@v1
        if: github.event_name  == 'pull_request'
        with:
          name: reportResult
          path: app/build/reports
  danger:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
        if: github.event_name  == 'pull_request'
      - uses: actions/download-artifact@v1
        if: github.event_name  == 'pull_request'
        with:
          name: testResult
          path: app/build/test-results/testReleaseUnitTest
      - uses: actions/download-artifact@v1
        if: github.event_name  == 'pull_request'
        with:
          name: reportResult
          path: app/build/reports
      - uses: actions/setup-ruby@v1
        if: github.event_name  == 'pull_request'
        with:
          ruby-version: '2.6'
      - uses: MeilCli/danger-action@master
        if: github.event_name  == 'pull_request'
        with:
          plugins_file: 'Gemfile'
          danger_file: 'Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}