name: Check Package

on: 
  schedule:
    #- cron: '0 8 * * 5' # every friday AM 8:00
    - cron: '7 * * * *'
jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant permission
      run: chmod +x gradlew
    - uses: MeilCli/gradle-update-check-action@master
      id: outdated
    - uses: 8398a7/action-slack@v2
      if: steps.outdated.outputs.has_maven_update != 'false'
      with:
        status: ${{ job.status }}
        text: ${{ steps.outdated.outputs.maven_update_text }}
        author_name: GitHub Actions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
